# Generated by Django 3.2.7 on 2021-09-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
    ]
