# Generated by Django 3.2.7 on 2021-09-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_remove_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='title',
        ),
    ]
