# Generated by Django 3.2.7 on 2021-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_rename_name_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.ImageField(default=1, upload_to='', verbose_name='images/'),
            preserve_default=False,
        ),
    ]
