# Generated by Django 3.2.7 on 2021-09-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0005_profile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='images',
        ),
    ]
