# Generated by Django 3.2.7 on 2021-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0007_profile_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='', verbose_name='images/')),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
